# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
env:
  WORKFLOW_VAR: 'my workflow var'
jobs:
  build:
    env:
      NODE_VERSION: 12
      JOB_VAR: 'my hob var'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Print step env var
      env:
        STEP_VAR: 'my step var'
      run: echo $STEP_VAR
    - run: echo $JOB_VAR
    - run: echo $WORKFLOW_VAR
    
