name: Exercíco 1
on:
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -  run: echo 'Primeiro Job :)'
  job2:
    runs-on: windows-latest
    steps:
      - run: echo Segundo Job
  job3:
    runs-on: macos-latest
    steps:
      - run: echo Terceiro Job
  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - run: date
