name: Exercíco 1
on:
  push:
    branches: [ main ]
jobs:
  multi-os:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - run: echo 'Multi-Steps'
  job4:
    runs-on: ubuntu-latest
    needs: [multi-os]
    steps:
      - run: date
