# This is a basic workflow to help you get started with Actions

name: Hello World

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:
#     inputs:
#       name:
#         description: 'Pessoa a ser cumprimentada'
#         required: true
#         default: 'Henrique Matos'
#       location:
#         description: 'Localização da pessoa no universo'
#         required: false
#         default: 'Planeta Terra'

jobs:
  job1:
    name: Primeiro Job
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Step 1
        run: env | sort

  job2:
    name: Segundo Job
    runs-on: windows-latest
    
    steps:
      - name: Step 1
        run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    name: Terceiro Job
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - name: Step Final
        run: echo Ultimo Step
